# docker-compose.yml
version: "3.5"

services:
  cardano-development:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER: plutus
        DOCKER_GID: ${DOCKER_GID}
    volumes:
      - ${HOST_PROJECT_PATH}/cardano-smart-contracts-examples:/home/plutus/workspace
      - ${HOST_PROJECT_PATH}/scripts:/home/plutus/workspace/scripts
      - ${HOST_PROJECT_PATH}/.priv:/home/plutus/workspace/.priv
      - ${HOST_PROJECT_PATH}/configs:/home/plutus/workspace/configs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    entrypoint: []
    #command: tail -f /dev/null  # Keep the container running indefinitely
    command: /bin/bash -c "sudo chmod +x /home/plutus/workspace/.devcontainer/scripts/on-create-container.sh && /home/plutus/workspace/.devcontainer/scripts/on-create-container.sh && tail -f /dev/null"


