version: "3.5"

services:
  cardano-wallet:
    container_name: cardano-wallet-container # Custom container name
    image: cardanofoundation/cardano-wallet:${CARDANO_WALLET_TAG:-latest}
    environment:
      - CARDANO_NETWORK=${CARDANO_NETWORK:-mainnet}
      - CARDANO_WALLET_PORT=${CARDANO_WALLET_PORT:-8090}
    networks:
      - cardano-network
    volumes:
      - ${CARDANO_WALLET_DB_PATH}:/wallet-db
      - node-ipc:/ipc
      - ${CONFIG_DIR_ABSOLUTE}:/configs
      - ${WORKSPACE_ROOT_DIR_ABSOLUTE}/scripts/init-cardano-wallet.sh:/init-cardano-wallet.sh # Mount the script into the container
    ports:
      - "${CARDANO_WALLET_PORT}:8090"

    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    entrypoint: []
    command: >
      /bin/bash -c "chmod +x /init-cardano-wallet.sh && /init-cardano-wallet.sh"
    # Ensure /init-cardano-wallet.sh includes the necessary logic to start the Cardano wallet correctly

  icarus:
    image: piotrstachyra/icarus:v2023-04-14
    networks:
      - cardano-network
    ports:
      - "4444:4444"
    restart: on-failure

networks:
  cardano-network:
    name: cardano-node_cardano-network
    external: true

volumes:
  node-ipc:
    name: cardano-node_node-ipc
    external: true
