name: Build Test

on:
  pull_request:
    branches:
      - main2  # Replace "main" with the branch you want to merge into

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.12.0'  # Adjust the version to match your project's requirements

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Test
      run: npm run test
