name: Continuous Integration

on:
  push:
    branches: [ main ]
    paths:
      - 'cardano-web3-frontend-template/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'cardano-web3-frontend-template/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        
    - name: Install dependencies
      run: npm ci
      working-directory: ./cardano-web3-frontend-template
      
    - name: Run tests
      run: npm test
      working-directory: ./cardano-web3-frontend-template
      
    - name: Build
      run: npm run build
      working-directory: ./cardano-web3-frontend-template